### ISSUE TITLE
Documentation: Swagger example for "async" endpoint needs to switch name fields between "loras" and "tis".

### ISSUE THREAD

**Issue by daveschumaker** [Haidra-Org/horde-sdk#119]
From what I'm understanding on how CivitAI's API response is, lora.id is a number (which should be casted to a string when sending to the Horde), while ti.id is a string.

<img width="556" alt="Screenshot 2024-01-15 at 9 20 47 AM" src="https://github.com/Haidra-Org/horde-sdk/assets/5395723/72b229b1-9bdd-401e-9d83-5f066b90346a">

TLDR; `GlowingRunesAIV6` is a TI and should be moved under the TI array.

I'm considering opening a PR myself, but my Python foo isn't super solid.

It looks like it's mentioned in a number of places here:
https://github.com/search?q=org%3AHaidra-Org%20GlowingRunesAIV6&type=code

**Comment by tazlin** [comment]
As mentioned on discord, this field value was historically valid. Other string values of LoRa model values continue to be valid today. The appearance of this string in this repo is something that happens automatically as a result of the API docs having it appear as a valid example. This string will no longer appear when the associated `AI-Horde` PR is merged and the next version of the SDK is published.
